
name: Generate fake-ip-filter of Clash
on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: wget
        run: |
          mkdir -p temp
          wget https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf -O temp/accelerated-domains.china.conf 
          wget https://raw.githubusercontent.com/wangqingyuan233/yaml/main/cf-ds.yaml -O temp/cf-ds.yaml
      - name: Generate list file
        run: |
          awk -F / '{print "+."$2}' temp/accelerated-domains.china.conf >> temp/fake_filter.list
          awk '{print "+."$1}' temp/cf-ds.yaml >> temp/fake_filter.list
      - name: Generate yaml file
        run: |
          echo fake-ip-filter: > Generate fake-ip-filter.yaml
          awk '{print "  - '\''"$1"'\''"}' temp/fake_filter.list >>  fake-ip-filter.yaml
      - name: upload yaml file
        run: |
          git config user.name "wangqingyuan233"
          git config user.email "wangqingyuan233@gmail.com"
          git add -A
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
